# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
  - stage: Snyk
    displayName: Scan code and container images 
    jobs:
    - job: Scan
      workspace:
        clean: all
      pool:
          vmImage: ubuntu-latest
      steps:
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'Snyk Service Connection'
            testType: 'app'
            monitorWhen: 'always'
            failOnIssues: false
            projectName: 'spring-boot-react-demo-app'
            organization: 'pilot-org-zd2'
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'Snyk Service Connection'
            testType: 'container'
            dockerImageName: 'eclipse-temurin:11'
            dockerfilePath: 'Dockerfile'
            monitorWhen: 'always'
            failOnIssues: false
            projectName: 'spring-boot-react-demo-app'
            organization: 'pilot-org-zd2'
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'Snyk Service Connection'
            testType: 'container'
            dockerImageName: 'node:12.4.0-alpine'
            dockerfilePath: './client/Dockerfile'
            monitorWhen: 'always'
            failOnIssues: false
            projectName: 'spring-boot-react-demo-app'
            organization: 'pilot-org-zd2'
       