# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
  - stage: Build
    displayName: Build and Publish Artifact 
    jobs:
    - job: Build
      workspace:
        clean: all
      pool:
          vmImage: ubuntu-latest
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
            replaceExistingArchive: true
        - publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
          displayName: 'Upload package'
          artifact: drop
        - task: Veracode@3
          inputs:
            ConnectionDetailsSelection: 'Endpoint'
            AnalysisService: 'SSU Service Connection'
            veracodeAppProfile: 'spring-boot-react-demo-app'
            version: '$(build.buildNumber)'
            filepath: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
            sandboxName: 'Development-Sandbox'
            maximumWaitTime: '360'
   