# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
  - stage: Build
    displayName: Build and Publish Artifact 
    jobs:
    - job: Build
      workspace:
        clean: all
      pool:
          vmImage: ubuntu-latest
      steps:
        - task: Maven@3
          displayName: "Build with Maven (Java)"
          inputs:
            mavenPomFile: 'pom.xml' 
            goals: 'package' # Optional
            javaHomeOption: 'JDKVersion' # Options: jDKVersion, path
            jdkVersionOption: 'default' # Optional. Options: default, 1.14, 1.13, 1.12, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
            jdkArchitectureOption: 'x64' # Optional. Options: x86, x64
            mavenVersionOption: 'Default' # Options: default, path
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
            replaceExistingArchive: true
        - publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
          displayName: 'Upload package'
          artifact: drop
        - task: Veracode@3
          inputs:
            ConnectionDetailsSelection: 'Endpoint'
            AnalysisService: 'SSU Service Connection'
            veracodeAppProfile: 'spring-boot-react-demo-app'
            version: '$(build.buildNumber)'
            filepath: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
            sandboxName: 'Development-Sandbox'
            maximumWaitTime: '360'
   